added factorial program using for loop
pythonites/Every-Python-Code-Ever pull request #7
Opened 2020-10-25 14:50 UTC by Pratik180198

Please add the label "Hactoberfest"

2020-10-25 16:01 UTC, pythonites requested changes
Hello @Pratik180198 
As this is a beginner level repo, I suggest you to please add comments to your program.
Though hacktoberfest-accepted level can be added but making the necessary changes will be good.

Thank you for the contribution.
Regards @pythonites

2020-10-25 16:59 UTC, Pratik180198 commented
Can you please help me how to changes request in the github

2020-10-25 17:09 UTC, pythonites commented
> Can you please help me how to changes request in the github

I think [this](https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo) is what you are looking for.

2020-10-25 18:32 UTC, Pratik180198 commented on factorial_01.py
> +try:
#The try block lets you test a block of code for errors.

2020-10-25 18:33 UTC, Pratik180198 commented on factorial_01.py
> +except:
#The except block lets you handle the error.

2020-10-25 18:34 UTC, Pratik180198 reviewed
Try and except comment added

2020-10-25 18:37 UTC, Pratik180198 commented
Sir please review that changes are right.

2020-10-26 04:07 UTC, pythonites approved these changes

2020-10-26 04:07 UTC, merged